Name1 = ("Nduta Ken Mbugua")
Grade1 = ("A-")
Class1 = ("Form 1 west")
Name2 = ("Joe Kahungu")
Grade2 = ("A")
Class2 = ("Form 4 west")
Name3 = ("Anne gachuhi")
Grade3 = ("B-")
Class3 = ("form 3 south")
print ("Students name:", Name1)
print ("Students grade:", Grade1)
print ("Students class:", Class1)
print ("Students name:", Name2)
print ("Students grade:", Grade2)
print ("Students class:", Class2)
print ("students name:", Name3)
print ("students grade:", Grade3)
print ("students class:", Class3)
       